name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.301'
      - run: |
          echo "Begin Build"
          # ls -a
          cd Everest/everest-app
          # echo "Install EF Tooling"
          # dotnet tool install --global dotnet-ef
          # dotnet tool restore
          # echo "Build DB"
          # dotnet ef database update --verbose
          echo "Build Application"
          dotnet build
