name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout setup-dotnet@v2
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.301'
      - name: Navigate
        run: |
          cd Everest/everest-app
          pwd
          ls -a
      - name: Build Application
        run: |
          cd Everest/everest-app
          dotnet restore
          dotnet build
