name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.301'
      - run: |
          echo "Everest Build"
          ls -a
          cd Everest/
          dotnet ef database update
          dotnet build
