name: CI
on:
  pull_request:
    branches: [develop]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.3'
      - run: |
          echo "Everest Build"
          ls -a
          cd Everest/
          dotnet build
