name: Trigger auto deployment for everest-production

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/everest-production-AutoDeployTrigger-329fef8c-fa27-4fa4-9e0c-3a0f76568f0a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: everestreleasecandidates.azurecr.io
          username: ${{ secrets.EVERESTPRODUCTION_REGISTRY_USERNAME }}
          password: ${{ secrets.EVERESTPRODUCTION_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: everestreleasecandidates.azurecr.io/everest-production:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.EVERESTPRODUCTION_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n everest-production -g everest --server everestreleasecandidates.azurecr.io --username  ${{ secrets.EVERESTPRODUCTION_REGISTRY_USERNAME }} --password ${{ secrets.EVERESTPRODUCTION_REGISTRY_PASSWORD }}
            az containerapp update -n everest-production -g everest --image everestreleasecandidates.azurecr.io/everest-production:${{ github.sha }}
